database:
  # (scheme)://(host):(port)/(database)
  # Keep the line commented out unless you get an obvious error message indicating that the driver was not found.
  # Default driver (net.azisaba.taxoffice.libs.org.mariadb.jdbc.Driver) points to the bundled MariaDB driver in the TaxOffice jar.
  #driver: net.azisaba.taxoffice.libs.org.mariadb.jdbc.Driver

  # change to jdbc:mysql if you want to use MySQL instead of MariaDB
  scheme: jdbc:mariadb
  hostname: localhost
  port: 3306
  name: tax_office
  username: tax_office
  password: tax_office
  properties:
    useSSL: true
    verifyServerCertificate: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true # use server-side prepared statements for performance boost
    socketTimeout: 30000 # milliseconds
    useLocalSessionState: true
    rewriteBatchedStatements: true
    maintainTimeStats: false

# Not used.
maximum-points: 1000000

autorank-requirement-description: "Pay at least %d points to the tax office"
