name: TaxOffice
version: 1.1.3
main: net.azisaba.taxoffice.TaxOffice
author: Azisaba Network
api-version: 1.13
softdepend:
  - Autorank
commands:
  taxoffice:
    permission: taxoffice.use_command
  ottt:
    permission: taxoffice.ottt
