name: TaxOffice
version: 1.1.1
main: net.azisaba.taxoffice.TaxOffice
author: Azisaba Network
softdepend:
  - Autorank
commands:
  taxoffice:
    permission: taxoffice.use_command
  ottt:
    permission: taxoffice.ottt
